# nixpacks.toml
[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.intl",
    "php82Extensions.zip",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.bcmath",
    "php82Extensions.gd",
    "php82Extensions.fileinfo",
    "nodejs"
]

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs --no-audit --no-interaction --prefer-dist --optimize-autoloader",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"